INSERT INTO site_pays VALUES (1, 'Belgique', 'Belgium');
INSERT INTO site_pays VALUES (2, 'France', 'France');
INSERT INTO site_pays VALUES (3, 'Luxembourg', 'Luxembourg');
INSERT INTO site_pays VALUES (4, 'Etats-Unis', 'USA');
INSERT INTO site_pays VALUES (5, 'Royaume-Uni', 'UK');
INSERT INTO site_pays VALUES (6, 'Allemagne', 'Deutschland');
INSERT INTO site_pays VALUES (7, 'Pays-Bas', 'Nederlands');
INSERT INTO site_pays VALUES (8, 'Espagne', 'Spain');
INSERT INTO site_pays VALUES (9, 'Suède', 'Sweden');
INSERT INTO site_pays VALUES (10, 'Portugal', 'Portugal');

INSERT INTO site_addresse VALUES (1, '48 rue de la Belgique', '5485', 1);
INSERT INTO site_addresse VALUES (2, '17 rue de la France', '78852', 2);
INSERT INTO site_addresse VALUES (3, '87 rue du Luxembourg', 'A365', 3);
INSERT INTO site_addresse VALUES (4, '48 rue des USA', 'AX585', 4);
INSERT INTO site_addresse VALUES (5, '48 rue de la GB', 'AZ5485', 5);
INSERT INTO site_addresse VALUES (6, '48 rue de l''Allemagne', '5485', 6);
INSERT INTO site_addresse VALUES (7, '48 rue des Pays Bas', 'AZA5485', 7);
INSERT INTO site_addresse VALUES (8, '48 rue de l''Espagne', '5485', 8);
INSERT INTO site_addresse VALUES (9, '48 rue de la Suède', '8884', 9);
INSERT INTO site_addresse VALUES (10, '48 rue du Portugal', '5485', 10);
INSERT INTO site_addresse VALUES (11, '48 route de la Belgique', '5485', 1);
INSERT INTO site_addresse VALUES (12, '17 route de la France', '78852', 2);
INSERT INTO site_addresse VALUES (13, '87 route du Luxembourg', 'A365', 3);
INSERT INTO site_addresse VALUES (14, '48 route des USA', 'AX585', 4);
INSERT INTO site_addresse VALUES (15, '48 route de la GB', 'AZ5485', 5);
INSERT INTO site_addresse VALUES (16, '48 route de l''Allemagne', '5485', 6);
INSERT INTO site_addresse VALUES (17, '48 route des Pays Bas', 'AZA5485', 7);
INSERT INTO site_addresse VALUES (18, '48 route de l''Espagne', '5485', 8);
INSERT INTO site_addresse VALUES (19, '48 route de la Suède', '8884', 9);
INSERT INTO site_addresse VALUES (20, '48 route du Portugal', '5485', 10);

INSERT INTO site_fournisseur VALUES (1, 'Amazon', 1);
INSERT INTO site_fournisseur VALUES (2, 'LDLC', 2);
INSERT INTO site_fournisseur VALUES (3, 'Rue du Commerce', 3);
INSERT INTO site_fournisseur VALUES (4, 'Pixmania', 4);
INSERT INTO site_fournisseur VALUES (5, 'Ebay', 5);
INSERT INTO site_fournisseur VALUES (6, 'Fnac', 6);
INSERT INTO site_fournisseur VALUES (7, 'Alternate', 7);
INSERT INTO site_fournisseur VALUES (8, 'Kelkoo', 8);
INSERT INTO site_fournisseur VALUES (9, 'Cdiscount', 9);
INSERT INTO site_fournisseur VALUES (10, 'Oka', 10);

INSERT INTO site_artiste VALUES (1, 'John Lennon', 1);
INSERT INTO site_artiste VALUES (2, 'Paul McCartney', 2);
INSERT INTO site_artiste VALUES (3, 'Ringo Starr', 3);
INSERT INTO site_artiste VALUES (4, 'George Harisson', 4);
INSERT INTO site_artiste VALUES (5, 'Jimmy Page', 5);
INSERT INTO site_artiste VALUES (6, 'Robert Plant', 6);
INSERT INTO site_artiste VALUES (7, 'John Bonham', 7);
INSERT INTO site_artiste VALUES (8, 'Freddy Mercury', 8);
INSERT INTO site_artiste VALUES (9, 'Mick Jagger', 9);
INSERT INTO site_artiste VALUES (10, 'Keith Richard', 10);

INSERT INTO site_editeur VALUES ('Universal');
INSERT INTO site_editeur VALUES ('Paramount');
INSERT INTO site_editeur VALUES ('Vivendi');
INSERT INTO site_editeur VALUES ('Galimard');
INSERT INTO site_editeur VALUES ('Sony');
INSERT INTO site_editeur VALUES ('EMI');
INSERT INTO site_editeur VALUES ('DreamWorks');
INSERT INTO site_editeur VALUES ('Warner Music');
INSERT INTO site_editeur VALUES ('Universal Music');
INSERT INTO site_editeur VALUES ('Warner Bros');