/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FreetaxStatsMainForm.java
 *
 * Created on 3 déc. 2011, 11:42:14
 */
package information_client;

import information_server.FreetaxStatsDesc;
import information_server.FreetaxStatsDescReponse;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author rapha
 */
public class FreetaxStatsMainForm extends javax.swing.JFrame {
    ObjectOutputStream _out;
    ObjectInputStream _in;

    FreetaxStatsMainForm(ObjectOutputStream out, ObjectInputStream in) {
        initComponents();
        
        this._out = out;
        this._in = in;                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        categorieText = new javax.swing.JTextField();
        donneesButton = new javax.swing.JButton();
        graph1DButton = new javax.swing.JButton();
        graph1DCompButton = new javax.swing.JButton();
        graph1DHistButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        numeroText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mois ou semaine:");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mois", "Semaine" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Catégorie:");

        categorieText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieTextActionPerformed(evt);
            }
        });

        donneesButton.setText("Données");
        donneesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donneesButtonActionPerformed(evt);
            }
        });

        graph1DButton.setText("Graphique 1D");
        graph1DButton.setToolTipText("");
        graph1DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graph1DButtonActionPerformed(evt);
            }
        });

        graph1DCompButton.setText("Graphique 1D Comp.");
        graph1DCompButton.setToolTipText("");

        graph1DHistButton.setText("Graphique 1D Hist.");
        graph1DHistButton.setActionCommand("");
        graph1DHistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graph1DHistButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Graphique 2D corrélé");

        jButton2.setText("Test d'hypothèse de comparaison des moyennes");
        jButton2.setToolTipText("");

        jLabel3.setText("Numero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categorieText, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(numeroText, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donneesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graph1DButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graph1DCompButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graph1DHistButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categorieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donneesButton)
                    .addComponent(graph1DButton)
                    .addComponent(graph1DCompButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graph1DHistButton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_typeComboBoxActionPerformed

private void categorieTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieTextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_categorieTextActionPerformed

private void graph1DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graph1DButtonActionPerformed

}//GEN-LAST:event_graph1DButtonActionPerformed

private void graph1DHistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graph1DHistButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_graph1DHistButtonActionPerformed

private void donneesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donneesButtonActionPerformed
    try {
        FreetaxStatsDesc desc;
        if ("".equals(this.numeroText.getText())) {
            // Mois choisi automatiquement
            desc = new FreetaxStatsDesc(
                this.categorieText.getText(), null, null
            );
        } else if (this.typeComboBox.getSelectedItem() == "Mois") {
            desc = new FreetaxStatsDesc(
                this.categorieText.getText(),
                Integer.parseInt(this.numeroText.getText()), null
            );
        } else {
            desc = new FreetaxStatsDesc(
                this.categorieText.getText(), null,
                Integer.parseInt(this.numeroText.getText())
            );
        }

        this._out.writeObject(desc);
        this._out.flush();
        
        FreetaxStatsDescReponse reponse
                = (FreetaxStatsDescReponse) this._in.readObject();
        
        new information_client.FreetaxStatsDesc(this, true, reponse).setVisible(true);
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_donneesButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categorieText;
    private javax.swing.JButton donneesButton;
    private javax.swing.JButton graph1DButton;
    private javax.swing.JButton graph1DCompButton;
    private javax.swing.JButton graph1DHistButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numeroText;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
