package information_client;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 28 oct. 2011, 14:27:36
 */
/**
 *
 * @author rapha
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        
        this.monnaiesList.setEnabled(false);
        this.meteoJoursList.setEnabled(false);
        
        this.alcoolsCheck.setEnabled(false);
        this.parfumsCheck.setEnabled(false);
        this.tabacsCheck.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ferryText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        voyageurText = new javax.swing.JTextField();
        monnaiesCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        monnaiesList = new javax.swing.JList();
        meteoCheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        meteoJoursList = new javax.swing.JList();
        taxesCheck = new javax.swing.JCheckBox();
        alcoolsCheck = new javax.swing.JCheckBox();
        parfumsCheck = new javax.swing.JCheckBox();
        tabacsCheck = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ferry:");

        jLabel2.setText("Nom voyageur:");

        voyageurText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voyageurTextActionPerformed(evt);
            }
        });

        monnaiesCheck.setText("Lister les cours monétaire");
        monnaiesCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monnaiesCheckActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(monnaiesList);

        meteoCheck.setText("Aficher la météo");
        meteoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meteoCheckActionPerformed(evt);
            }
        });

        jLabel3.setText("Jour(s) du mois:");

        jScrollPane2.setViewportView(meteoJoursList);

        taxesCheck.setText("Lister les produits hors taxes");
        taxesCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxesCheckActionPerformed(evt);
            }
        });

        alcoolsCheck.setText("Alcools ");

        parfumsCheck.setText("Parfums");

        tabacsCheck.setText("Tabacs");
        tabacsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabacsCheckActionPerformed(evt);
            }
        });

        jButton1.setText("Envoyer la demande");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ferryText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(voyageurText, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(monnaiesCheck)
                                            .addComponent(meteoCheck))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                            .addComponent(taxesCheck)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(alcoolsCheck)
                        .addGap(18, 18, 18)
                        .addComponent(parfumsCheck)
                        .addGap(18, 18, 18)
                        .addComponent(tabacsCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ferryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(voyageurText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monnaiesCheck)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(meteoCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(taxesCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alcoolsCheck)
                    .addComponent(parfumsCheck)
                    .addComponent(tabacsCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void voyageurTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voyageurTextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_voyageurTextActionPerformed

private void monnaiesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monnaiesCheckActionPerformed
    this.monnaiesList.setEnabled(this.monnaiesCheck.isSelected());
}//GEN-LAST:event_monnaiesCheckActionPerformed

private void meteoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meteoCheckActionPerformed
    this.meteoJoursList.setEnabled(this.meteoCheck.isSelected());
}//GEN-LAST:event_meteoCheckActionPerformed

private void tabacsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabacsCheckActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tabacsCheckActionPerformed

private void taxesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxesCheckActionPerformed
    boolean checked = this.taxesCheck.isSelected();
    this.alcoolsCheck.setEnabled(checked);
    this.parfumsCheck.setEnabled(checked);
    this.tabacsCheck.setEnabled(checked);
}//GEN-LAST:event_taxesCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alcoolsCheck;
    private javax.swing.JTextField ferryText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox meteoCheck;
    private javax.swing.JList meteoJoursList;
    private javax.swing.JCheckBox monnaiesCheck;
    private javax.swing.JList monnaiesList;
    private javax.swing.JCheckBox parfumsCheck;
    private javax.swing.JCheckBox tabacsCheck;
    private javax.swing.JCheckBox taxesCheck;
    private javax.swing.JTextField voyageurText;
    // End of variables declaration//GEN-END:variables
}
