package mail_client;

import java.io.File;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author rapha
 */
public class NouveauMessage extends javax.swing.JDialog {
    private Session _smtpSession;
    private String _email;

    /** Creates new form NouveauMessage */
    public NouveauMessage(java.awt.Frame parent, boolean modal, 
            Session smtpSession, String email)
    {
        this(parent, modal, smtpSession, email, "", "");
    }

    NouveauMessage(java.awt.Frame parent, boolean modal, 
            Session smtpSession, String email, String destinataire,
            String sujet)
    {
        super(parent, modal);
        this._smtpSession = smtpSession;
        this._email = email;
        
        initComponents();
        
        this.destinataireText.setText(destinataire);
        this.sujetText.setText(sujet);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        sujetText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        destinataireText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextArea();
        envoyerButton = new javax.swing.JButton();
        erreurLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        messageTypeCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        piecesJointesList = new javax.swing.JList();
        ajoutPieceButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau message");

        jLabel1.setText("Sujet:");

        jLabel2.setText("Destinataire:");

        destinataireText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinataireTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Message:");

        messageText.setColumns(20);
        messageText.setRows(5);
        jScrollPane1.setViewportView(messageText);

        envoyerButton.setText("Envoyer");
        envoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerButtonActionPerformed(evt);
            }
        });

        erreurLabel.setForeground(new java.awt.Color(204, 0, 0));

        jLabel4.setText("Type message:");

        messageTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FRONTIER_INFO", "FRONTIER_INFO_ACK", "FRONTIER_WANTED", "FRONTIER_WANTED_ACK", "FRONTIER_WANTED_TOO_LATE" }));

        jLabel5.setText("Pièces jointes:");

        piecesJointesList.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(piecesJointesList);

        ajoutPieceButton.setText("Ajouter une pièce jointe");
        ajoutPieceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutPieceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sujetText, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                                    .addComponent(destinataireText, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)))
                            .addComponent(jLabel3))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(erreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(envoyerButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(631, Short.MAX_VALUE))
                    .addComponent(ajoutPieceButton)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(messageTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(destinataireText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sujetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajoutPieceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(erreurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(envoyerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void destinataireTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinataireTextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_destinataireTextActionPerformed

private void envoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerButtonActionPerformed
    try {
        MimeMessage msg = new MimeMessage(this._smtpSession);
        msg.setFrom(new InternetAddress(this._email));
        msg.setRecipient(
            Message.RecipientType.TO,
            new InternetAddress(this.destinataireText.getText())
        );
        msg.setSubject(
            this.messageTypeCombo.getSelectedItem() + ": "
            + this.sujetText.getText()
        );
        
        Multipart parts = new MimeMultipart();
        
        // Ajout de la partie texte du message
        MimeBodyPart body = new MimeBodyPart();
        body.setText(this.messageText.getText());
        parts.addBodyPart(body);
        
        // Ajout des pièces jointes
        for (Object piece_obj : this.piecesJointesList.getSelectedValuesList()) {
            MimeBodyPart piece = new MimeBodyPart();
            DataSource so = new FileDataSource((String) piece_obj);
            piece.setDataHandler(new DataHandler(so));
            piece.setFileName((String) piece_obj);
            parts.addBodyPart(piece);
        }
        
        msg.setContent(parts);
        
        Transport.send(msg);
        
        this.dispose();
    } catch (MessagingException ex) {
        this.erreurLabel.setText(ex.getMessage());
        ex.printStackTrace();
    }
}//GEN-LAST:event_envoyerButtonActionPerformed

private void ajoutPieceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutPieceButtonActionPerformed
    JFileChooser fc = new JFileChooser();
    int returnVal = fc.showOpenDialog(this);

    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        
        DefaultListModel model = (DefaultListModel) this.piecesJointesList.getModel();
        
        model.addElement(file.getName());
    }
}//GEN-LAST:event_ajoutPieceButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutPieceButton;
    private javax.swing.JTextField destinataireText;
    private javax.swing.JButton envoyerButton;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageText;
    private javax.swing.JComboBox messageTypeCombo;
    private javax.swing.JList piecesJointesList;
    private javax.swing.JTextField sujetText;
    // End of variables declaration//GEN-END:variables
}
